### PR TITLE
sys-devel/gcc-7.3.0 version bump

### PR DESCRIPTION
**Pull request by devurandom**
This drops all RISC-V patches under the assumption that all of them went
 upstream for 7.3.0.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
I think we should be able to drop this ebuild entirely, right?

**Comment by devurandom** [comment]
That did not work for me, because of the keywords (Gentoo tree has no riscv keywords, yet).

**Comment by palmer-dabbelt** [comment]
I think this should do it: https://github.com/riscv/riscv-gentoo/blob/master/profiles/arch/riscv/package.accept_keywords#L129

**Comment by devurandom** [comment]
7.3.0 in Gentoo is currently only ~amd64. Hence I adjusted the accepted keywords accordingly. I also removed the 7.2.0 version from the overlay under the assumption that all patches went upstream already.

**Comment by devurandom** [comment]
This still does not work. When running `crossdev -t riscv64-unkown-elf --stage4`, `emerge` aborts for gcc stage1 with a keyword issue. In `/etc/portage/package.keywords/cross-riscv64-unknown-elf`, `crossdev` set `riscv ~riscv -amd64 -~amd64` for all of binutils, gcc, newlib and gdb. I need to investigate, why crossdev does this.

**Pull request closed without merging**
